# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: giovannyg
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/sign-in.handler
    events:
      - httpApi:
          path: /sign-in
          method: POST
  signup:
    handler: src/functions/sign-up.handler
    events:
      - httpApi:
          path: /sign-up
          method: POST
